//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "raydium_token_launches")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub contract_address: String,
  pub creator_address: String,
  pub evaluation: Option<String>,
  #[sea_orm(column_type = "Float")]
  pub launch_liquidity: f32,
  #[sea_orm(column_type = "Float")]
  pub launch_liquidity_usd: f32,
  pub rugged_at: Option<i32>,
  pub lifespan: Option<i32>,
  pub meta: Option<Json>,
  pub has_boost: bool,
  pub created_at: DateTime,
  pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
