//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wallets")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub title: String,
  pub chain: String,
  #[sea_orm(unique)]
  pub address: String,
  pub encrypted_private_key: String,
  pub secret_key: String,
  pub salt: String,
  pub encryption_schema: String,
  pub user_id: i32,
  pub created_at: DateTime,
  pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::onchain_transactions::Entity")]
  OnchainTransactions,
  #[sea_orm(has_many = "super::trade_orders::Entity")]
  TradeOrders,
  #[sea_orm(
    belongs_to = "super::users::Entity",
    from = "Column::UserId",
    to = "super::users::Column::Id",
    on_update = "NoAction",
    on_delete = "NoAction"
  )]
  Users,
}

impl Related<super::onchain_transactions::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::OnchainTransactions.def()
  }
}

impl Related<super::trade_orders::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::TradeOrders.def()
  }
}

impl Related<super::users::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Users.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
